// Banco de questões (português) baseado no Scrum Guide 2020 e nos domínios do PSPO I.
// A ordem é a mesma nos dois idiomas: o índice de cada questão é o id usado no rodízio.
// topic: backlog | po | events | value | release | fundamentals
// type: "single" (uma resposta), "multi" (várias respostas), "tf" (verdadeiro/falso)
// answer: índices das opções corretas
window.QUESTIONS = [
  { topic: "fundamentals", type: "multi",
    q: "Quais são os três pilares do empirismo no Scrum? (Escolha 3)",
    options: ["Transparência", "Inspeção", "Adaptação", "Previsibilidade", "Comprometimento"],
    answer: [0, 1, 2],
    exp: "O Scrum se baseia no empirismo, sustentado por transparência, inspeção e adaptação." },
  { topic: "fundamentals", type: "multi",
    q: "Quais são os valores do Scrum? (Escolha 5)",
    options: ["Comprometimento", "Foco", "Abertura", "Respeito", "Coragem", "Velocidade", "Documentação"],
    answer: [0, 1, 2, 3, 4],
    exp: "Os cinco valores do Scrum são Comprometimento, Foco, Abertura, Respeito e Coragem." },
  { topic: "fundamentals", type: "tf",
    q: "O Scrum é uma metodologia completa que define todas as práticas necessárias para desenvolver um produto.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "O Scrum é um framework propositalmente incompleto. Ele define apenas as partes necessárias para implementar a teoria Scrum." },
  { topic: "fundamentals", type: "single",
    q: "Além do empirismo, em qual outro conceito o Scrum se fundamenta?",
    options: ["Lean thinking", "Gestão em cascata", "Six Sigma", "PMBOK"],
    answer: [0],
    exp: "O Scrum combina empirismo e lean thinking, que reduz desperdício e foca no essencial." },
  { topic: "events", type: "single",
    q: "Qual é a duração máxima de uma Sprint?",
    options: ["Duas semanas", "Um mês", "Seis semanas", "Não há limite"],
    answer: [1],
    exp: "Sprints têm duração fixa de um mês ou menos, para manter consistência e limitar o risco." },
  { topic: "fundamentals", type: "multi",
    q: "Quais são os artefatos do Scrum? (Escolha 3)",
    options: ["Product Backlog", "Sprint Backlog", "Incremento", "Burndown Chart", "Roadmap do produto"],
    answer: [0, 1, 2],
    exp: "Os três artefatos são Product Backlog, Sprint Backlog e Incremento. Burndown e roadmap são práticas opcionais." },
  { topic: "fundamentals", type: "single",
    q: "Qual compromisso está associado ao Incremento?",
    options: ["Meta do Produto", "Meta da Sprint", "Definição de Pronto", "Definição de Preparado"],
    answer: [2],
    exp: "Product Backlog → Meta do Produto; Sprint Backlog → Meta da Sprint; Incremento → Definição de Pronto." },
  { topic: "fundamentals", type: "single",
    q: "Qual compromisso está associado ao Product Backlog?",
    options: ["Meta da Sprint", "Meta do Produto", "Definição de Pronto", "Visão da empresa"],
    answer: [1],
    exp: "A Meta do Produto é o compromisso do Product Backlog e descreve um estado futuro do produto." },
  { topic: "fundamentals", type: "tf",
    q: "Uma nova Sprint começa imediatamente após o término da Sprint anterior.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "Segundo o Scrum Guide, uma nova Sprint começa imediatamente após a conclusão da anterior." },
  { topic: "events", type: "multi",
    q: "Quais eventos ocorrem dentro da Sprint? (Escolha 4)",
    options: ["Sprint Planning", "Daily Scrum", "Sprint Review", "Sprint Retrospective", "Release Planning"],
    answer: [0, 1, 2, 3],
    exp: "A Sprint contém todos os demais eventos: Planning, Daily, Review e Retrospective. Release Planning não é um evento Scrum." },
  { topic: "events", type: "single",
    q: "Qual é o timebox máximo da Sprint Planning para uma Sprint de um mês?",
    options: ["2 horas", "4 horas", "8 horas", "1 dia inteiro sem limite"],
    answer: [2],
    exp: "Sprint Planning: máximo de 8 horas para Sprints de um mês. Para Sprints mais curtas, o evento costuma ser menor." },
  { topic: "events", type: "single",
    q: "Qual é o timebox máximo da Sprint Review para uma Sprint de um mês?",
    options: ["1 hora", "2 horas", "3 horas", "4 horas"],
    answer: [3],
    exp: "Sprint Review: máximo de 4 horas para uma Sprint de um mês." },
  { topic: "events", type: "single",
    q: "Qual é o timebox máximo da Sprint Retrospective para uma Sprint de um mês?",
    options: ["1 hora", "2 horas", "3 horas", "4 horas"],
    answer: [2],
    exp: "Sprint Retrospective: máximo de 3 horas para uma Sprint de um mês." },
  { topic: "events", type: "single",
    q: "Qual é a duração da Daily Scrum?",
    options: ["15 minutos", "30 minutos", "Depende do tamanho da Sprint", "Até 1 hora"],
    answer: [0],
    exp: "A Daily Scrum é um evento de 15 minutos para os Developers, independentemente do tamanho da Sprint." },
  { topic: "fundamentals", type: "tf",
    q: "Um Scrum Team geralmente tem 10 pessoas ou menos.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "O Scrum Guide indica que o Scrum Team é tipicamente de 10 pessoas ou menos." },
  { topic: "fundamentals", type: "single",
    q: "Quem é responsável por criar um Incremento utilizável a cada Sprint?",
    options: ["O Product Owner", "O Scrum Master", "Os Developers", "Os stakeholders"],
    answer: [2],
    exp: "Os Developers são responsáveis por criar qualquer aspecto de um Incremento utilizável a cada Sprint." },
  { topic: "fundamentals", type: "single",
    q: "Quem é responsável por todas as atividades relacionadas ao produto, como colaboração com stakeholders, verificação, operação e pesquisa?",
    options: ["Apenas o Product Owner", "Apenas os Developers", "O Scrum Team", "A gerência"],
    answer: [2],
    exp: "O Scrum Team inteiro é responsável por todas as atividades relacionadas ao produto." },
  { topic: "fundamentals", type: "tf",
    q: "Dentro de um Scrum Team existem sub-times e hierarquias para organizar o trabalho.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "Não há sub-times nem hierarquias dentro de um Scrum Team. É uma unidade coesa focada em um objetivo por vez." },
  { topic: "events", type: "single",
    q: "Quem pode cancelar uma Sprint?",
    options: ["O Scrum Master", "Os Developers", "O Product Owner", "Os stakeholders"],
    answer: [2],
    exp: "Somente o Product Owner tem autoridade para cancelar a Sprint, o que faz sentido se a Meta da Sprint se tornar obsoleta." },
  { topic: "events", type: "single",
    q: "Quando uma Sprint deve ser cancelada?",
    options: ["Quando o time não vai concluir todos os itens", "Quando a Meta da Sprint se torna obsoleta", "Quando um stakeholder pede", "Quando um Developer sai de férias"],
    answer: [1],
    exp: "Uma Sprint pode ser cancelada se a Meta da Sprint se tornar obsoleta." },
  { topic: "fundamentals", type: "tf",
    q: "Se múltiplos Scrum Teams trabalham no mesmo produto, eles devem compartilhar o mesmo Product Backlog e o mesmo Product Owner.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "Vários Scrum Teams no mesmo produto compartilham a mesma Meta do Produto, o mesmo Product Backlog e o mesmo Product Owner." },
  { topic: "po", type: "single",
    q: "Pelo que o Product Owner é responsável (accountable)?",
    options: ["Maximizar o valor do produto resultante do trabalho do Scrum Team", "Gerenciar as tarefas dos Developers", "Garantir que a Daily Scrum aconteça", "Definir as estimativas dos itens"],
    answer: [0],
    exp: "O Product Owner é responsável por maximizar o valor do produto resultante do trabalho do Scrum Team." },
  { topic: "po", type: "tf",
    q: "O Product Owner é uma pessoa, e não um comitê.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "O Product Owner é uma única pessoa. Ele pode representar as necessidades de muitos stakeholders no Product Backlog." },
  { topic: "po", type: "multi",
    q: "Quais atividades fazem parte do gerenciamento eficaz do Product Backlog pelo Product Owner? (Escolha 4)",
    options: ["Desenvolver e comunicar explicitamente a Meta do Produto", "Criar e comunicar claramente os itens do Product Backlog", "Ordenar os itens do Product Backlog", "Garantir que o Product Backlog seja transparente, visível e compreendido", "Atribuir tarefas a cada Developer"],
    answer: [0, 1, 2, 3],
    exp: "Essas são as quatro atividades listadas no Scrum Guide. Atribuir tarefas não é papel do Product Owner: os Developers se auto-gerenciam." },
  { topic: "po", type: "tf",
    q: "O Product Owner pode delegar o trabalho de gerenciar o Product Backlog para outras pessoas, mas continua sendo o responsável (accountable).",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "O Product Owner pode fazer o trabalho ou delegá-lo, mas continua sendo accountable." },
  { topic: "po", type: "single",
    q: "Um stakeholder quer mudar a prioridade de um item do Product Backlog. O que deve fazer?",
    options: ["Pedir diretamente aos Developers", "Convencer o Product Owner", "Pedir ao Scrum Master que mude a ordem", "Alterar o Product Backlog ele mesmo"],
    answer: [1],
    exp: "Quem quiser mudar o Product Backlog pode fazê-lo tentando convencer o Product Owner." },
  { topic: "po", type: "single",
    q: "Para o Product Owner ter sucesso, o que a organização inteira deve fazer?",
    options: ["Aprovar cada decisão dele em comitê", "Respeitar as decisões dele", "Indicar um gerente para supervisioná-lo", "Permitir que ele trabalhe apenas meio período"],
    answer: [1],
    exp: "Para que o Product Owner tenha sucesso, a organização inteira deve respeitar suas decisões, visíveis no conteúdo e na ordem do Product Backlog." },
  { topic: "po", type: "multi",
    q: "Quais destas são formas de o Product Owner aumentar o valor entregue? (Escolha 2)",
    options: ["Ordenar o Product Backlog para entregar primeiro o que gera mais valor", "Colaborar com stakeholders e usuários para validar hipóteses", "Exigir que os Developers trabalhem horas extras", "Pular a Sprint Review para economizar tempo"],
    answer: [0, 1],
    exp: "Ordenar por valor e validar hipóteses com usuários aumentam o valor. Horas extras e eliminar eventos reduzem a transparência e a sustentabilidade." },
  { topic: "po", type: "tf",
    q: "O Product Owner deve participar da Daily Scrum obrigatoriamente.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "A Daily Scrum é para os Developers. Product Owner e Scrum Master participam como Developers apenas se estiverem trabalhando ativamente em itens do Sprint Backlog." },
  { topic: "po", type: "single",
    q: "O que melhor descreve o papel do Product Owner em relação à visão do produto?",
    options: ["Recebe a visão pronta e apenas repassa", "Desenvolve e comunica a Meta do Produto alinhada à visão", "Não tem relação com a visão", "Documenta a visão apenas no início do projeto"],
    answer: [1],
    exp: "O Product Owner é responsável por desenvolver e comunicar explicitamente a Meta do Produto, que dá direção ao Scrum Team." },
  { topic: "po", type: "single",
    q: "Um Product Owner tem dificuldade em ser ouvido pela organização e as decisões dele são frequentemente revertidas. Quem deve ajudar?",
    options: ["Os Developers, assumindo as decisões", "O Scrum Master, servindo à organização e ao Product Owner", "Ninguém. O PO deve resolver sozinho", "O cliente principal, substituindo o PO"],
    answer: [1],
    exp: "O Scrum Master serve à organização e ao Product Owner, ajudando a remover impedimentos e a promover o entendimento do Scrum." },
  { topic: "po", type: "tf",
    q: "O Product Owner pode ser também um Developer no mesmo Scrum Team.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "O Scrum Guide não proíbe. Se o PO trabalha ativamente em itens do Sprint Backlog, também atua como Developer, mas deve estar ciente do conflito de foco." },
  { topic: "po", type: "single",
    q: "Qual é a principal medida de sucesso de um Product Owner?",
    options: ["Quantidade de itens entregues", "Velocidade do time", "Valor entregue e resultados (outcomes) obtidos", "Cumprimento do plano inicial"],
    answer: [2],
    exp: "O sucesso é medido por valor e resultados (outcomes), não por produção (output) ou aderência ao plano." },
  { topic: "backlog", type: "single",
    q: "O que é o Product Backlog?",
    options: ["Uma lista fixa de requisitos aprovada no início", "Uma lista emergente e ordenada do que é necessário para melhorar o produto", "Uma lista de tarefas técnicas da Sprint", "O plano de projeto com datas"],
    answer: [1],
    exp: "O Product Backlog é uma lista emergente e ordenada do que é necessário para melhorar o produto e é a única fonte de trabalho do Scrum Team." },
  { topic: "backlog", type: "tf",
    q: "O Product Backlog é a única fonte de trabalho realizado pelo Scrum Team.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "O Scrum Guide define o Product Backlog como a única fonte de trabalho do Scrum Team." },
  { topic: "backlog", type: "single",
    q: "O que é o refinamento do Product Backlog?",
    options: ["Um evento formal com timebox de 2 horas", "A atividade contínua de quebrar e detalhar itens em itens menores e mais precisos", "A aprovação dos itens pelos stakeholders", "A reunião onde o PO apresenta a priorização final"],
    answer: [1],
    exp: "Refinamento é uma atividade contínua (não um evento) de quebrar e detalhar itens, adicionando descrição, ordem e tamanho." },
  { topic: "backlog", type: "single",
    q: "Quem é responsável pelo dimensionamento (estimativa) dos itens do Product Backlog?",
    options: ["O Product Owner", "O Scrum Master", "Os Developers que farão o trabalho", "Os stakeholders"],
    answer: [2],
    exp: "Os Developers que farão o trabalho são responsáveis pelo dimensionamento. O PO pode influenciá-los ajudando a entender e escolher trade-offs." },
  { topic: "backlog", type: "tf",
    q: "Todos os itens do Product Backlog precisam estar totalmente detalhados antes de entrarem no backlog.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "Itens no topo tendem a estar mais refinados. Itens mais abaixo podem ser vagos. O nível de detalhe é proporcional à proximidade de serem trabalhados." },
  { topic: "backlog", type: "single",
    q: "Quando um item do Product Backlog é considerado pronto para ser selecionado na Sprint Planning?",
    options: ["Quando o PO assinou o documento de requisitos", "Quando pode ser concluído pelo Scrum Team dentro de uma Sprint", "Quando todos os stakeholders aprovaram", "Quando tem pontos de história atribuídos pelo Scrum Master"],
    answer: [1],
    exp: "Itens que podem ser concluídos dentro de uma Sprint são considerados prontos para seleção na Sprint Planning." },
  { topic: "backlog", type: "multi",
    q: "Quais atributos os itens do Product Backlog costumam ter após o refinamento? (Escolha 3)",
    options: ["Descrição", "Ordem", "Tamanho", "Nome do Developer responsável", "Aprovação formal do cliente"],
    answer: [0, 1, 2],
    exp: "O refinamento adiciona detalhes como descrição, ordem e tamanho. Os atributos podem variar conforme o domínio." },
  { topic: "backlog", type: "tf",
    q: "O Product Backlog deve ser ordenado estritamente por valor de negócio, sem considerar risco ou dependências.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "O PO decide a ordem considerando valor, risco, dependências, aprendizado e outros fatores. Não há uma única regra." },
  { topic: "backlog", type: "single",
    q: "Um Product Backlog com centenas de itens muito detalhados para os próximos dois anos é um sinal de quê?",
    options: ["Excelente planejamento", "Possível desperdício e falta de adaptação", "Requisito obrigatório do Scrum", "Maturidade do time"],
    answer: [1],
    exp: "Detalhar demais itens distantes gera desperdício, porque eles provavelmente mudarão. O backlog é emergente." },
  { topic: "backlog", type: "tf",
    q: "Itens do Product Backlog precisam ser escritos no formato de User Stories.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "O Scrum não exige User Stories. É uma prática complementar opcional." },
  { topic: "backlog", type: "single",
    q: "Qual é o objetivo da Meta do Produto?",
    options: ["Listar todas as features a serem entregues", "Descrever um estado futuro do produto que serve de alvo para o Scrum Team", "Definir o orçamento", "Estabelecer prazos fixos de entrega"],
    answer: [1],
    exp: "A Meta do Produto descreve um estado futuro do produto e é o objetivo de longo prazo do Scrum Team." },
  { topic: "backlog", type: "tf",
    q: "O Scrum Team deve cumprir (ou abandonar) uma Meta do Produto antes de assumir a próxima.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "O Scrum Team deve cumprir ou abandonar um objetivo antes de assumir o próximo." },
  { topic: "backlog", type: "single",
    q: "Quem pode adicionar itens ao Product Backlog?",
    options: ["Apenas o Product Owner", "Qualquer pessoa, desde que o Product Owner continue responsável pelo conteúdo e ordem", "Apenas os stakeholders", "Apenas o Scrum Master"],
    answer: [1],
    exp: "Outras pessoas podem contribuir com itens, mas o Product Owner continua accountable pelo Product Backlog." },
  { topic: "backlog", type: "multi",
    q: "Quais destes podem fazer parte do Product Backlog? (Escolha 3)",
    options: ["Novas funcionalidades", "Correções de bugs", "Melhorias técnicas e de infraestrutura", "Ata das reuniões de diretoria"],
    answer: [0, 1, 2],
    exp: "O Product Backlog contém tudo que é necessário para melhorar o produto: features, correções, trabalho técnico, experimentos etc." },
  { topic: "backlog", type: "single",
    q: "Quanto tempo do Scrum Team deve ser dedicado ao refinamento?",
    options: ["Exatamente 10% da Sprint", "Não há valor definido; o time decide conforme a necessidade", "Um dia por Sprint", "Nenhum, isso é trabalho exclusivo do PO"],
    answer: [1],
    exp: "O Scrum Guide 2020 não define um percentual. O Scrum Team decide quanto refinamento é necessário." },
  { topic: "value", type: "single",
    q: "Qual é a melhor definição de 'produto' segundo o Scrum Guide?",
    options: ["Um software entregue ao cliente", "Um veículo para entregar valor, com limites claros, stakeholders e usuários conhecidos", "Qualquer documento produzido pelo time", "Uma lista de features"],
    answer: [1],
    exp: "Um produto é um veículo para entregar valor. Possui limites claros, stakeholders e usuários bem definidos. Pode ser um serviço, algo físico ou abstrato." },
  { topic: "value", type: "single",
    q: "Qual é a diferença entre output e outcome?",
    options: ["São sinônimos", "Output é o que é produzido; outcome é a mudança de comportamento ou resultado gerado", "Outcome é a quantidade de features; output é o lucro", "Output é medido pelo cliente; outcome pelo time"],
    answer: [1],
    exp: "Output = o que entregamos (features). Outcome = o resultado gerado para usuários e organização. O PO foca em outcomes." },
  { topic: "value", type: "tf",
    q: "Velocidade (velocity) é uma boa métrica para medir o valor entregue ao cliente.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "Velocity mede capacidade e produção, não valor. Valor é medido por resultados como satisfação, receita e uso." },
  { topic: "value", type: "multi",
    q: "Quais são indicadores de valor que um Product Owner pode acompanhar? (Escolha 3)",
    options: ["Satisfação do cliente", "Receita por funcionário", "Taxa de uso de funcionalidades", "Número de horas trabalhadas", "Quantidade de linhas de código"],
    answer: [0, 1, 2],
    exp: "Satisfação, receita e uso indicam valor. Horas e linhas de código medem esforço, não valor." },
  { topic: "value", type: "single",
    q: "O Evidence-Based Management (EBM) organiza a medição de valor em quais áreas-chave (Key Value Areas)?",
    options: ["Custo, Prazo, Escopo e Qualidade", "Valor Atual, Valor Não Realizado, Habilidade de Inovar e Tempo para o Mercado", "Velocidade, Burndown, Bugs e Horas", "Receita, Lucro, Ações e Dividendos"],
    answer: [1],
    exp: "O EBM usa quatro Key Value Areas: Current Value, Unrealized Value, Ability to Innovate e Time to Market." },
  { topic: "value", type: "single",
    q: "Na abordagem EBM, o que mede o 'Valor Não Realizado' (Unrealized Value)?",
    options: ["O valor entregue hoje", "O valor potencial que poderia ser obtido atendendo melhor às necessidades do mercado", "O custo de manutenção", "O tempo entre ideia e entrega"],
    answer: [1],
    exp: "Unrealized Value representa o valor potencial futuro que a organização poderia capturar." },
  { topic: "value", type: "single",
    q: "Na abordagem EBM, a área 'Habilidade de Inovar' (Ability to Innovate) é afetada negativamente por qual fator?",
    options: ["Dívida técnica elevada", "Feedback frequente de usuários", "Releases frequentes", "Equipes multifuncionais"],
    answer: [0],
    exp: "Dívida técnica consome capacidade que poderia ir para inovação, reduzindo a Ability to Innovate." },
  { topic: "value", type: "tf",
    q: "Entregar mais funcionalidades sempre gera mais valor.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "Muitas funcionalidades raramente ou nunca são usadas. Valor vem de resolver problemas reais, não de volume de entregas." },
  { topic: "release", type: "single",
    q: "Por que lançar Incrementos com frequência ajuda a maximizar valor?",
    options: ["Porque agrada a gerência", "Porque gera feedback rápido do mercado e reduz o risco", "Porque o Scrum exige um release por Sprint", "Porque diminui a necessidade de testes"],
    answer: [1],
    exp: "Releases frequentes permitem validar hipóteses cedo, aprender e adaptar, reduzindo o risco de construir a coisa errada." },
  { topic: "release", type: "tf",
    q: "No Scrum, um Incremento só pode ser liberado ao final da Sprint, após a Sprint Review.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "Um Incremento pode ser entregue aos stakeholders antes do fim da Sprint. A Sprint Review não deve ser vista como um portão para liberar valor." },
  { topic: "value", type: "single",
    q: "O que significa 'Tempo para o Mercado' (Time to Market) no EBM?",
    options: ["O tempo de duração do projeto", "A capacidade de entregar rapidamente novas capacidades, serviços ou produtos", "O tempo até o produto dar lucro", "O tempo gasto em marketing"],
    answer: [1],
    exp: "Time to Market expressa a capacidade da organização de entregar novas capacidades rapidamente e aprender com o feedback." },
  { topic: "value", type: "single",
    q: "Um produto já tem alta satisfação de clientes e domina o mercado, mas a dívida técnica está alta. Qual é o maior risco?",
    options: ["Nenhum risco", "Perda futura da capacidade de inovar e responder ao mercado", "Aumento imediato de receita", "Excesso de feedback"],
    answer: [1],
    exp: "Com alta dívida técnica, a Ability to Innovate e o Time to Market caem, ameaçando o valor futuro." },
  { topic: "value", type: "multi",
    q: "Quais práticas ajudam a validar se uma ideia de produto gera valor antes de construí-la por completo? (Escolha 2)",
    options: ["Construir um experimento ou MVP", "Testar a hipótese com usuários reais", "Documentar tudo antes de começar", "Aguardar a aprovação anual do orçamento"],
    answer: [0, 1],
    exp: "Experimentos, MVPs e testes com usuários validam hipóteses com baixo custo e aprendizado rápido." },
  { topic: "events", type: "single",
    q: "Qual é o principal evento para inspecionar o resultado da Sprint com stakeholders?",
    options: ["Sprint Planning", "Daily Scrum", "Sprint Review", "Sprint Retrospective"],
    answer: [2],
    exp: "Na Sprint Review, o Scrum Team e os stakeholders inspecionam o resultado da Sprint e determinam adaptações futuras." },
  { topic: "events", type: "tf",
    q: "A Sprint Review deve ser tratada como uma apresentação formal, com slides, para aprovação dos stakeholders.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "A Sprint Review é uma sessão de trabalho colaborativa, não apenas uma apresentação." },
  { topic: "po", type: "single",
    q: "Durante a Sprint, um stakeholder pede uma nova funcionalidade diretamente a um Developer. O que deve acontecer?",
    options: ["O Developer implementa imediatamente", "O pedido é direcionado ao Product Owner, que avalia e ordena no Product Backlog", "O Scrum Master recusa o pedido", "A Sprint é cancelada"],
    answer: [1],
    exp: "Novos pedidos passam pelo Product Owner, que decide se e onde o item entra no Product Backlog." },
  { topic: "po", type: "multi",
    q: "Quais destas são boas práticas do Product Owner para envolver stakeholders? (Escolha 3)",
    options: ["Convidá-los para a Sprint Review", "Manter o Product Backlog transparente e acessível", "Colaborar continuamente para entender necessidades", "Esconder o Product Backlog para evitar pressão", "Aceitar todos os pedidos sem análise"],
    answer: [0, 1, 2],
    exp: "Transparência e colaboração contínua são fundamentais. Esconder o backlog ou aceitar tudo sem análise prejudica o valor." },
  { topic: "po", type: "tf",
    q: "O Product Owner é o único ponto de contato permitido entre o Scrum Team e os stakeholders.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "Os Developers podem e devem interagir com stakeholders e usuários. O PO continua responsável pelo Product Backlog." },
  { topic: "po", type: "single",
    q: "Dois stakeholders importantes pedem funcionalidades conflitantes. O que o Product Owner deve fazer?",
    options: ["Construir as duas", "Tomar a decisão com base no valor e na Meta do Produto, comunicando de forma transparente", "Deixar o Scrum Master decidir", "Pedir aos Developers para votar"],
    answer: [1],
    exp: "O PO decide com base no valor, na Meta do Produto e em evidências, explicando a decisão de forma transparente." },
  { topic: "events", type: "single",
    q: "Qual é um resultado esperado da Sprint Review?",
    options: ["Um Product Backlog revisado com prováveis itens para a próxima Sprint", "Um plano de melhoria do processo", "A assinatura de aceite do cliente", "A lista de tarefas da próxima Sprint"],
    answer: [0],
    exp: "O resultado da Sprint Review é um Product Backlog revisado que define prováveis itens para a próxima Sprint." },
  { topic: "events", type: "multi",
    q: "Quais tópicos podem ser discutidos na Sprint Review? (Escolha 3)",
    options: ["O que foi realizado na Sprint", "Mudanças no ambiente ou mercado", "O que fazer em seguida para otimizar valor", "Avaliação de desempenho individual dos Developers"],
    answer: [0, 1, 2],
    exp: "A Review inspeciona o que foi feito e o que mudou, e decide os próximos passos. Avaliações individuais não fazem parte." },
  { topic: "events", type: "tf",
    q: "A Sprint Retrospective é o principal evento para o Scrum Team colaborar com os stakeholders sobre o produto.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "A Retrospective é do Scrum Team e foca em qualidade e efetividade. A colaboração com stakeholders sobre o produto acontece principalmente na Sprint Review." },
  { topic: "po", type: "single",
    q: "Qual é a diferença mais adequada entre cliente e usuário?",
    options: ["São sempre a mesma pessoa", "O cliente paga ou decide comprar; o usuário utiliza o produto, e podem ser pessoas diferentes", "Usuário é interno, cliente é externo", "Não existe diferença relevante para o PO"],
    answer: [1],
    exp: "Cliente e usuário podem ser diferentes. O PO precisa entender as necessidades de ambos." },
  { topic: "events", type: "multi",
    q: "Quais tópicos são tratados na Sprint Planning? (Escolha 3)",
    options: ["Por que esta Sprint é valiosa?", "O que pode ser feito nesta Sprint?", "Como o trabalho escolhido será feito?", "Quem será avaliado ao final?"],
    answer: [0, 1, 2],
    exp: "A Sprint Planning aborda três tópicos: Por quê (Meta da Sprint), O quê e Como." },
  { topic: "events", type: "single",
    q: "Quem define a Meta da Sprint?",
    options: ["Apenas o Product Owner", "O Scrum Team inteiro, em colaboração", "O Scrum Master", "Os stakeholders"],
    answer: [1],
    exp: "O Product Owner propõe como o produto pode aumentar seu valor, e todo o Scrum Team colabora para definir a Meta da Sprint." },
  { topic: "release", type: "single",
    q: "Quem seleciona quantos itens do Product Backlog entram na Sprint?",
    options: ["O Product Owner", "Os Developers", "O Scrum Master", "A gerência"],
    answer: [1],
    exp: "Os Developers selecionam os itens do Product Backlog, em conversa com o Product Owner, considerando capacidade e desempenho passado." },
  { topic: "events", type: "single",
    q: "A quem pertence o Sprint Backlog?",
    options: ["Ao Product Owner", "Ao Scrum Master", "Aos Developers", "Aos stakeholders"],
    answer: [2],
    exp: "O Sprint Backlog é um plano feito pelos e para os Developers." },
  { topic: "events", type: "tf",
    q: "Durante a Sprint, o escopo pode ser esclarecido e renegociado com o Product Owner conforme se aprende mais.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "O escopo pode ser esclarecido e renegociado com o PO, desde que a Meta da Sprint não seja comprometida." },
  { topic: "events", type: "tf",
    q: "Durante a Sprint, podem ser feitas mudanças que coloquem em risco a Meta da Sprint, se o stakeholder solicitar.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "Nenhuma mudança que coloque em risco a Meta da Sprint deve ser feita durante a Sprint." },
  { topic: "release", type: "multi",
    q: "Quais práticas podem ser usadas para prever o progresso em direção a uma meta? (Escolha 3)",
    options: ["Burn-down", "Burn-up", "Cumulative flow", "Diagrama de Gantt com datas fixas obrigatórias"],
    answer: [0, 1, 2],
    exp: "O Scrum Guide cita burn-downs, burn-ups e cumulative flows como práticas úteis, mas lembra que não substituem o empirismo." },
  { topic: "release", type: "tf",
    q: "Práticas de previsão como burn-down eliminam a incerteza sobre o futuro.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "Essas práticas são úteis, mas não substituem o empirismo. Em ambientes complexos, o futuro é incerto; apenas o que já aconteceu pode orientar decisões." },
  { topic: "release", type: "single",
    q: "Com que frequência o progresso em direção à Meta do Produto deve ser inspecionado?",
    options: ["Apenas no fim do projeto", "Pelo menos na Sprint Review", "Somente quando a gerência pedir", "Uma vez por ano"],
    answer: [1],
    exp: "O progresso em direção à Meta do Produto é inspecionado e adaptado pelo menos na Sprint Review." },
  { topic: "release", type: "single",
    q: "Uma empresa pergunta ao Product Owner a data exata em que todo o escopo atual estará pronto. Qual é a melhor resposta?",
    options: ["Dar uma data fixa e garantir que será cumprida", "Fornecer uma previsão baseada em dados empíricos, atualizando-a conforme o aprendizado", "Recusar-se a responder", "Pedir que o Scrum Master defina"],
    answer: [1],
    exp: "O PO pode oferecer previsões baseadas em desempenho passado, deixando claro que elas evoluem com novas informações." },
  { topic: "release", type: "tf",
    q: "O orçamento de um produto desenvolvido com Scrum pode ser revisto a cada Sprint com base no valor entregue.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "Como cada Sprint entrega um Incremento, a organização pode decidir continuar, ajustar ou parar o investimento a cada ciclo." },
  { topic: "events", type: "single",
    q: "Qual é o papel do Product Owner na Sprint Planning?",
    options: ["Garantir que os participantes estejam preparados para discutir os itens mais importantes e como se ligam à Meta do Produto", "Decidir quantos itens os Developers devem fazer", "Criar o plano técnico da Sprint", "Apenas observar"],
    answer: [0],
    exp: "O PO garante que os participantes estejam preparados para discutir os itens mais importantes do Product Backlog e sua relação com a Meta do Produto." },
  { topic: "release", type: "single",
    q: "O que é a Definição de Pronto?",
    options: ["Uma lista de tarefas de cada item", "Uma descrição formal do estado do Incremento quando ele atende às medidas de qualidade exigidas", "O aceite do cliente", "Os critérios de aceite de cada User Story"],
    answer: [1],
    exp: "A Definição de Pronto é uma descrição formal do estado do Incremento quando atende às medidas de qualidade exigidas para o produto." },
  { topic: "release", type: "tf",
    q: "Se um item do Product Backlog não atender à Definição de Pronto, ele pode ser apresentado na Sprint Review como concluído parcialmente.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "Se não atende à Definição de Pronto, o item não pode ser liberado nem apresentado na Sprint Review. Ele volta ao Product Backlog para consideração futura." },
  { topic: "release", type: "single",
    q: "Se a Definição de Pronto faz parte dos padrões da organização, o que o Scrum Team deve fazer?",
    options: ["Ignorá-la e criar uma própria", "Segui-la como mínimo", "Pedir dispensa", "Usá-la apenas nas últimas Sprints"],
    answer: [1],
    exp: "Se a organização tem um padrão, todos os Scrum Teams devem segui-lo como mínimo. Caso contrário, o Scrum Team cria uma adequada ao produto." },
  { topic: "release", type: "single",
    q: "Vários Scrum Teams trabalham no mesmo produto. Como deve ser a Definição de Pronto?",
    options: ["Cada time define a sua, sem relação", "Eles devem definir e cumprir mutuamente a mesma Definição de Pronto", "Somente o primeiro time define", "Não precisa existir"],
    answer: [1],
    exp: "Se vários Scrum Teams trabalham juntos em um produto, eles devem definir e cumprir mutuamente a mesma Definição de Pronto." },
  { topic: "release", type: "tf",
    q: "Reduzir a qualidade é uma forma aceitável de cumprir a Meta da Sprint quando o prazo está apertado.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "Durante a Sprint, a qualidade não diminui." },
  { topic: "release", type: "single",
    q: "Qual é a consequência de acumular dívida técnica para o Product Owner?",
    options: ["Mais velocidade no longo prazo", "Menor transparência sobre o real estado do produto e redução do valor futuro", "Nenhuma, é responsabilidade dos Developers", "Aumento automático da qualidade"],
    answer: [1],
    exp: "Dívida técnica reduz a transparência, desacelera entregas futuras e diminui a capacidade de inovar. Isso impacta diretamente o valor." },
  { topic: "release", type: "tf",
    q: "Um Incremento deve ser utilizável, mesmo que o Product Owner decida não liberá-lo.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "Cada Incremento deve ser utilizável. A decisão de liberar é separada da decisão de que ele está pronto." },
  { topic: "release", type: "single",
    q: "Vários Incrementos podem ser criados dentro de uma Sprint?",
    options: ["Não, apenas um no fim", "Sim, e a soma deles é apresentada na Sprint Review", "Somente com autorização da gerência", "Somente em Sprints de um mês"],
    answer: [1],
    exp: "Múltiplos Incrementos podem ser criados em uma Sprint. A soma é apresentada na Sprint Review, mas eles podem ser entregues antes." },
  { topic: "events", type: "single",
    q: "Qual é o propósito da Sprint Retrospective?",
    options: ["Inspecionar o Incremento com stakeholders", "Planejar formas de aumentar qualidade e efetividade", "Atualizar o Product Backlog", "Avaliar o desempenho do Product Owner"],
    answer: [1],
    exp: "A Retrospective tem como propósito planejar formas de aumentar a qualidade e a efetividade." },
  { topic: "events", type: "single",
    q: "Qual é o propósito da Daily Scrum?",
    options: ["Reportar status ao Product Owner", "Inspecionar o progresso em direção à Meta da Sprint e adaptar o Sprint Backlog", "Resolver todos os problemas técnicos", "Distribuir tarefas aos Developers"],
    answer: [1],
    exp: "A Daily Scrum serve para inspecionar o progresso em direção à Meta da Sprint e adaptar o Sprint Backlog quando necessário." },
  { topic: "events", type: "tf",
    q: "Os Developers podem escolher qualquer estrutura e técnica para a Daily Scrum, desde que ela foque no progresso em direção à Meta da Sprint.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "O Scrum Guide 2020 removeu as três perguntas obrigatórias. Os Developers escolhem a estrutura." },
  { topic: "fundamentals", type: "single",
    q: "Qual é o termo usado no Scrum Guide 2020 para descrever que o Scrum Team decide internamente quem faz o quê, quando e como?",
    options: ["Auto-organizado", "Autogerenciável", "Autocrático", "Autônomo total"],
    answer: [1],
    exp: "O Scrum Guide 2020 descreve Scrum Teams como autogerenciáveis (self-managing)." },
  { topic: "fundamentals", type: "multi",
    q: "Como o Scrum Master serve ao Product Owner? (Escolha 3)",
    options: ["Ajudando a encontrar técnicas para definir a Meta do Produto e gerenciar o Product Backlog", "Ajudando o Scrum Team a entender a necessidade de itens claros e concisos", "Facilitando a colaboração com stakeholders quando solicitado", "Definindo a ordem do Product Backlog no lugar do PO"],
    answer: [0, 1, 2],
    exp: "O Scrum Master apoia o PO com técnicas, entendimento e facilitação, mas não toma as decisões de produto." },
  { topic: "events", type: "tf",
    q: "Os eventos do Scrum são projetados para criar regularidade e minimizar a necessidade de reuniões não definidas no Scrum.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "Os eventos criam regularidade e reduzem reuniões extras, preferencialmente no mesmo horário e local." },
  { topic: "events", type: "single",
    q: "O que acontece com os itens concluídos do Sprint Backlog quando a Sprint é cancelada?",
    options: ["São descartados", "O Product Owner os revisa; se forem utilizáveis, podem ser aceitos", "São automaticamente liberados", "Voltam ao topo do backlog obrigatoriamente"],
    answer: [1],
    exp: "Itens concluídos são revisados, e o PO pode aceitar os que forem utilizáveis. Os incompletos são reestimados e devolvidos ao Product Backlog." },
  { topic: "events", type: "tf",
    q: "A Sprint Review é o último evento da Sprint.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "A Sprint Retrospective é o último evento da Sprint." },
  { topic: "po", type: "single",
    q: "Uma organização quer nomear três pessoas como Product Owners do mesmo produto, cada uma com uma parte do backlog. O que o Scrum recomenda?",
    options: ["Seguir com três POs, um por time", "Ter um único Product Owner para o produto, que pode contar com apoio de outras pessoas", "Formar um comitê de produto", "Eliminar o papel de PO"],
    answer: [1],
    exp: "Um produto tem um único Product Owner e um único Product Backlog. Outras pessoas podem ajudar, mas a accountability é de uma pessoa." },
  { topic: "po", type: "multi",
    q: "Quais características ajudam um Product Owner a ser eficaz? (Escolha 3)",
    options: ["Ter autoridade para tomar decisões sobre o produto", "Conhecer o domínio e o mercado", "Estar disponível para o Scrum Team e stakeholders", "Controlar como os Developers fazem o trabalho técnico"],
    answer: [0, 1, 2],
    exp: "Autoridade, conhecimento do domínio e disponibilidade são essenciais. Os Developers decidem como fazer o trabalho." },
  { topic: "value", type: "single",
    q: "Um Product Owner percebe que uma funcionalidade lançada há três meses quase não é usada. Qual é a melhor ação?",
    options: ["Ignorar, pois já foi entregue", "Investigar o motivo com dados e usuários e decidir se melhora, remove ou mantém", "Pedir mais funcionalidades parecidas", "Culpar os Developers"],
    answer: [1],
    exp: "O PO usa evidências para decidir. Funcionalidades pouco usadas geram custo de manutenção e podem ser melhoradas ou removidas." },
  { topic: "po", type: "single",
    q: "Como o Product Owner pode tornar transparente para a organização o que o Scrum Team fará a seguir?",
    options: ["Através de um Product Backlog visível, ordenado e compreensível", "Enviando relatórios de horas", "Com reuniões semanais de status obrigatórias", "Mantendo uma planilha privada"],
    answer: [0],
    exp: "O Product Backlog transparente mostra a todos o que o Scrum Team vai trabalhar e em qual ordem." },
  { topic: "events", type: "tf",
    q: "Uma Sprint pode ser estendida se o time não conseguir terminar os itens planejados.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "A Sprint tem duração fixa. Não se estende a Sprint; os itens não concluídos voltam ao Product Backlog." },
  { topic: "events", type: "single",
    q: "Qual é o efeito de Sprints muito longas?",
    options: ["Menor complexidade e menor risco", "A Meta da Sprint pode se tornar inválida, a complexidade e o risco aumentam", "Maior frequência de feedback", "Nenhum efeito"],
    answer: [1],
    exp: "Quando o horizonte da Sprint é longo demais, a Meta pode se tornar inválida, e a complexidade e o risco aumentam." },
  { topic: "release", type: "tf",
    q: "Critérios de aceite de um item substituem a Definição de Pronto.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "Critérios de aceite são específicos de cada item. A Definição de Pronto se aplica a todo o Incremento. Os dois se complementam." },
  { topic: "backlog", type: "multi",
    q: "Quais fatores o Product Owner pode considerar ao ordenar o Product Backlog? (Escolha 4)",
    options: ["Valor de negócio", "Risco", "Dependências", "Retorno sobre investimento (ROI)", "Preferência pessoal de um Developer"],
    answer: [0, 1, 2, 3],
    exp: "A ordenação considera valor, risco, dependências, ROI, aprendizado e outros fatores que o PO julgar relevantes para maximizar valor." },
  { topic: "backlog", type: "single",
    q: "Dois itens têm valor de negócio semelhante. O item A tem alto risco técnico e o item B é simples. O que pode justificar colocar o item A antes?",
    options: ["Nada, itens simples sempre vêm primeiro", "Reduzir o risco cedo, aprendendo antes que o custo de mudança aumente", "Manter os Developers ocupados", "Agradar a gerência"],
    answer: [1],
    exp: "Tratar riscos cedo gera aprendizado e reduz incerteza. O risco é um fator legítimo de ordenação." },
  { topic: "backlog", type: "tf",
    q: "O Product Owner pode reordenar o Product Backlog a qualquer momento, inclusive durante a Sprint.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "O Product Backlog é dinâmico. O PO pode reordená-lo a qualquer momento. O que não muda durante a Sprint é a Meta da Sprint." },
  { topic: "backlog", type: "single",
    q: "Quem decide a ordem final dos itens do Product Backlog?",
    options: ["Os stakeholders, por votação", "O Product Owner", "Os Developers", "O Scrum Master"],
    answer: [1],
    exp: "O Product Owner é o único responsável pela ordem do Product Backlog. Outros influenciam, mas a decisão é dele." },
  { topic: "backlog", type: "single",
    q: "Quem participa do refinamento do Product Backlog?",
    options: ["Apenas o Product Owner", "O Product Owner e os Developers, podendo incluir stakeholders", "Apenas os Developers", "Apenas o Scrum Master"],
    answer: [1],
    exp: "O refinamento é colaborativo: PO e Developers trabalham juntos, e stakeholders podem contribuir quando útil." },
  { topic: "backlog", type: "tf",
    q: "O refinamento do Product Backlog é um evento oficial do Scrum, com timebox definido.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "Refinamento é uma atividade contínua, não um evento. Uma referência comum é até 10% da capacidade do time, mas isso não é regra do Scrum Guide 2020." },
  { topic: "backlog", type: "single",
    q: "Qual é o principal objetivo do refinamento?",
    options: ["Garantir que os itens do topo estejam prontos para a Sprint Planning", "Aprovar formalmente os requisitos", "Atribuir itens a cada Developer", "Calcular o orçamento do projeto"],
    answer: [0],
    exp: "O refinamento quebra e detalha itens para que os do topo fiquem prontos para serem selecionados na Sprint Planning." },
  { topic: "backlog", type: "single",
    q: "Na Sprint Planning, os Developers não entendem bem os itens do topo do backlog. Qual é a causa mais provável?",
    options: ["Refinamento insuficiente antes da Sprint Planning", "Sprint longa demais", "Excesso de Daily Scrums", "Definição de Pronto muito rígida"],
    answer: [0],
    exp: "Itens mal compreendidos na Planning normalmente indicam que o refinamento contínuo não foi suficiente." },
  { topic: "backlog", type: "multi",
    q: "O que torna um Product Backlog transparente? (Escolha 3)",
    options: ["Estar visível para todos os interessados", "Ser compreendido pelo Scrum Team e stakeholders", "Refletir a ordem real do que será feito", "Ser acessível apenas ao Product Owner"],
    answer: [0, 1, 2],
    exp: "Transparência exige visibilidade, entendimento compartilhado e fidelidade à realidade. Esconder o backlog prejudica o empirismo." },
  { topic: "backlog", type: "tf",
    q: "O Product Backlog nunca está completo e evolui conforme o produto e o mercado mudam.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "O Product Backlog é emergente: muda constantemente para refletir o que o produto precisa para ser valioso." },
  { topic: "backlog", type: "single",
    q: "Um item no fim do Product Backlog não é priorizado há mais de um ano. O que o Product Owner deve considerar?",
    options: ["Mantê-lo para sempre", "Avaliar se ainda faz sentido e removê-lo se não gerar valor", "Movê-lo ao topo para não esquecer", "Pedir que o Scrum Master decida"],
    answer: [1],
    exp: "Remover itens que não geram valor mantém o backlog enxuto e transparente. Isso é parte da gestão do backlog." },
  { topic: "backlog", type: "single",
    q: "Como o Product Owner pode influenciar a estimativa feita pelos Developers?",
    options: ["Impondo um número", "Ajudando-os a entender os itens e a escolher trade-offs", "Não pode influenciar de forma alguma", "Pedindo que o Scrum Master revise"],
    answer: [1],
    exp: "O PO influencia ajudando a entender o item e os trade-offs, mas quem estima são os Developers que farão o trabalho." },
  { topic: "backlog", type: "tf",
    q: "O Product Backlog deve ser ordenado pela ordem de chegada dos pedidos dos stakeholders.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "O backlog é ordenado para maximizar valor, não por ordem de chegada ou por stakeholder." },
  { topic: "backlog", type: "single",
    q: "Um item grande e vago está próximo do topo do Product Backlog. Qual é a melhor ação?",
    options: ["Colocá-lo na Sprint como está", "Refiná-lo, quebrando-o em itens menores que caibam em uma Sprint", "Movê-lo para o fim", "Excluí-lo"],
    answer: [1],
    exp: "Itens próximos de serem trabalhados devem ser refinados em partes menores, que caibam em uma Sprint." },
  { topic: "value", type: "single",
    q: "Qual é a relação entre visão do produto e Meta do Produto?",
    options: ["São a mesma coisa", "A visão dá o propósito e a direção de longo prazo; a Meta do Produto é um alvo concreto rumo a essa visão", "A Meta do Produto substitui a visão", "A visão é definida pelos Developers"],
    answer: [1],
    exp: "A visão descreve o propósito do produto. A Meta do Produto é um objetivo de longo prazo que move o produto nessa direção." },
  { topic: "value", type: "tf",
    q: "A Meta do Produto faz parte do Product Backlog.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "A Meta do Produto está no Product Backlog. O restante do backlog emerge para definir o que cumprirá a meta." },
  { topic: "value", type: "multi",
    q: "Quais características tornam uma visão de produto eficaz? (Escolha 3)",
    options: ["Clara e fácil de comunicar", "Focada no problema do cliente e no valor", "Inspiradora para o time e os stakeholders", "Uma lista detalhada de funcionalidades"],
    answer: [0, 1, 2],
    exp: "Uma boa visão é clara, centrada no valor para o cliente e inspira. Lista de features não é visão." },
  { topic: "value", type: "single",
    q: "A Meta do Produto foi alcançada. O que acontece em seguida?",
    options: ["O Scrum Team é desfeito obrigatoriamente", "O Product Owner define uma nova Meta do Produto, se ainda houver valor a entregar", "A Sprint é cancelada", "O produto é congelado"],
    answer: [1],
    exp: "Cumprida a meta, o PO pode definir a próxima, sempre buscando maximizar valor." },
  { topic: "value", type: "single",
    q: "Qual é o foco principal do Evidence-Based Management (EBM)?",
    options: ["Medir a produtividade individual", "Usar evidências para medir e melhorar o valor entregue", "Controlar prazos e orçamento", "Comparar times entre si"],
    answer: [1],
    exp: "O EBM ajuda organizações a medir valor com evidências e a melhorar a capacidade de entregá-lo." },
  { topic: "value", type: "single",
    q: "Na abordagem EBM, o que o Valor Atual (Current Value) mede?",
    options: ["O valor potencial futuro", "O valor que o produto entrega hoje para clientes e organização", "O tempo de entrega", "A dívida técnica"],
    answer: [1],
    exp: "Current Value mede o valor entregue hoje, como satisfação de clientes e funcionários e receita." },
  { topic: "events", type: "single",
    q: "Na Sprint Planning, qual contribuição principal se espera do Product Owner?",
    options: ["Explicar como o produto pode aumentar seu valor na Sprint e discutir os itens do topo", "Dividir os itens em tarefas técnicas", "Definir quanto cada Developer vai trabalhar", "Apenas assistir"],
    answer: [0],
    exp: "O PO propõe como aumentar o valor (o Por quê) e discute com os Developers os itens do topo do backlog (o O quê)." },
  { topic: "events", type: "single",
    q: "Quem decide como os itens selecionados serão transformados em Incremento na Sprint Planning?",
    options: ["O Product Owner", "Os Developers", "O Scrum Master", "Os stakeholders"],
    answer: [1],
    exp: "O Como é decisão exclusiva dos Developers. O PO esclarece dúvidas e negocia trade-offs, sem ditar como fazer." },
  { topic: "events", type: "single",
    q: "Qual é o papel do Product Owner na Sprint Review?",
    options: ["Ser protagonista na colaboração com stakeholders, discutindo o Incremento, o mercado e adaptando o Product Backlog", "Aprovar ou reprovar individualmente os Developers", "Apresentar slides de status", "Não participa"],
    answer: [0],
    exp: "Na Review, o PO lidera a conversa sobre o progresso rumo à Meta do Produto, mudanças no mercado e o que fazer a seguir." },
  { topic: "events", type: "tf",
    q: "Na Sprint Review, o Product Owner pode discutir o progresso em direção à Meta do Produto e possíveis datas de entrega.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "A Review é o momento de inspecionar o progresso rumo à Meta do Produto e ajustar previsões e o backlog." },
  { topic: "events", type: "tf",
    q: "O Product Owner participa da Sprint Retrospective como membro do Scrum Team.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "O PO é membro do Scrum Team e participa da Retrospective, que inspeciona pessoas, interações, processos e ferramentas." },
  { topic: "events", type: "single",
    q: "O Product Owner quer participar da Daily Scrum para acompanhar o progresso. Qual é a abordagem correta?",
    options: ["Ele conduz a reunião e cobra status", "A Daily é dos Developers; o PO só participa ativamente se estiver atuando como Developer", "É proibido estar presente", "Deve substituir o Scrum Master"],
    answer: [1],
    exp: "A Daily Scrum é para os Developers. O PO participa ativamente apenas se estiver trabalhando em itens do Sprint Backlog." },
  { topic: "release", type: "single",
    q: "Quem decide quando liberar um Incremento para o mercado?",
    options: ["Os Developers", "O Scrum Master", "O Product Owner", "A área de operações, sempre"],
    answer: [2],
    exp: "A decisão de release é do Product Owner, com base no valor acumulado, no mercado e nos riscos." },
  { topic: "release", type: "tf",
    q: "O valor só é realmente entregue quando um Incremento que atende à Definição de Pronto é utilizado pelos usuários.",
    options: ["Verdadeiro", "Falso"],
    answer: [0],
    exp: "Trabalho não pronto não gera valor. O valor se concretiza quando um Incremento pronto e utilizável chega aos usuários." },
  { topic: "release", type: "single",
    q: "Um Incremento está pronto, mas o Product Owner decide não liberá-lo agora. Isso é válido?",
    options: ["Não, todo Incremento deve ser liberado imediatamente", "Sim, a decisão de liberar é do PO, mas o Incremento deve estar utilizável", "Somente se o Scrum Master concordar", "Só na última Sprint"],
    answer: [1],
    exp: "Estar pronto e ser liberado são decisões separadas. O PO pode acumular valor e liberar depois, quando fizer sentido." },
  { topic: "release", type: "multi",
    q: "Quais fatores o Product Owner pode considerar ao decidir um release? (Escolha 3)",
    options: ["Valor acumulado para os usuários", "Momento de mercado e concorrência", "Riscos de lançar ou de esperar", "O número de horas trabalhadas na Sprint"],
    answer: [0, 1, 2],
    exp: "O release considera valor, mercado e risco. Horas trabalhadas não indicam valor." },
  { topic: "release", type: "tf",
    q: "Release Planning é um evento obrigatório do Scrum.",
    options: ["Verdadeiro", "Falso"],
    answer: [1],
    exp: "Release Planning não é um evento do Scrum. O planejamento de releases é uma prática que o PO pode usar à sua maneira." },
];
