// Banco de questões (inglês) baseado no Scrum Guide 2020 e nos domínios do PSPO I.
// A ordem é a mesma nos dois idiomas: o índice de cada questão é o id usado no rodízio.
// topic: backlog | po | events | value | release | fundamentals
// type: "single" (uma resposta), "multi" (várias respostas), "tf" (verdadeiro/falso)
// answer: índices das opções corretas
window.QUESTIONS_EN = [
  { topic: "fundamentals", type: "multi",
    q: "What are the three pillars of empiricism in Scrum? (Choose 3)",
    options: ["Transparency", "Inspection", "Adaptation", "Predictability", "Commitment"],
    answer: [0, 1, 2],
    exp: "Scrum is founded on empiricism, which is upheld by transparency, inspection, and adaptation." },
  { topic: "fundamentals", type: "multi",
    q: "What are the Scrum values? (Choose 5)",
    options: ["Commitment", "Focus", "Openness", "Respect", "Courage", "Velocity", "Documentation"],
    answer: [0, 1, 2, 3, 4],
    exp: "The five Scrum values are Commitment, Focus, Openness, Respect, and Courage." },
  { topic: "fundamentals", type: "tf",
    q: "Scrum is a complete methodology that defines all the practices needed to develop a product.",
    options: ["True", "False"],
    answer: [1],
    exp: "Scrum is a purposefully incomplete framework. It defines only the parts required to implement Scrum theory." },
  { topic: "fundamentals", type: "single",
    q: "Besides empiricism, what other concept is Scrum founded on?",
    options: ["Lean thinking", "Waterfall management", "Six Sigma", "PMBOK"],
    answer: [0],
    exp: "Scrum combines empiricism with lean thinking, which reduces waste and focuses on the essentials." },
  { topic: "events", type: "single",
    q: "What is the maximum length of a Sprint?",
    options: ["Two weeks", "One month", "Six weeks", "There is no limit"],
    answer: [1],
    exp: "Sprints are fixed-length events of one month or less to create consistency and limit risk." },
  { topic: "fundamentals", type: "multi",
    q: "What are the Scrum artifacts? (Choose 3)",
    options: ["Product Backlog", "Sprint Backlog", "Increment", "Burndown chart", "Product roadmap"],
    answer: [0, 1, 2],
    exp: "The three artifacts are the Product Backlog, the Sprint Backlog, and the Increment. Burndown charts and roadmaps are optional practices." },
  { topic: "fundamentals", type: "single",
    q: "Which commitment is associated with the Increment?",
    options: ["Product Goal", "Sprint Goal", "Definition of Done", "Definition of Ready"],
    answer: [2],
    exp: "Product Backlog → Product Goal; Sprint Backlog → Sprint Goal; Increment → Definition of Done." },
  { topic: "fundamentals", type: "single",
    q: "Which commitment is associated with the Product Backlog?",
    options: ["Sprint Goal", "Product Goal", "Definition of Done", "Company vision"],
    answer: [1],
    exp: "The Product Goal is the commitment for the Product Backlog and describes a future state of the product." },
  { topic: "fundamentals", type: "tf",
    q: "A new Sprint starts immediately after the conclusion of the previous Sprint.",
    options: ["True", "False"],
    answer: [0],
    exp: "According to the Scrum Guide, a new Sprint starts immediately after the conclusion of the previous Sprint." },
  { topic: "events", type: "multi",
    q: "Which events take place within the Sprint? (Choose 4)",
    options: ["Sprint Planning", "Daily Scrum", "Sprint Review", "Sprint Retrospective", "Release Planning"],
    answer: [0, 1, 2, 3],
    exp: "The Sprint is a container for all other events: Sprint Planning, Daily Scrum, Sprint Review, and Sprint Retrospective. Release Planning is not a Scrum event." },
  { topic: "events", type: "single",
    q: "What is the maximum timebox for Sprint Planning in a one-month Sprint?",
    options: ["2 hours", "4 hours", "8 hours", "A full day with no limit"],
    answer: [2],
    exp: "Sprint Planning is timeboxed to a maximum of 8 hours for a one-month Sprint. For shorter Sprints, the event is usually shorter." },
  { topic: "events", type: "single",
    q: "What is the maximum timebox for the Sprint Review in a one-month Sprint?",
    options: ["1 hour", "2 hours", "3 hours", "4 hours"],
    answer: [3],
    exp: "The Sprint Review is timeboxed to a maximum of 4 hours for a one-month Sprint." },
  { topic: "events", type: "single",
    q: "What is the maximum timebox for the Sprint Retrospective in a one-month Sprint?",
    options: ["1 hour", "2 hours", "3 hours", "4 hours"],
    answer: [2],
    exp: "The Sprint Retrospective is timeboxed to a maximum of 3 hours for a one-month Sprint." },
  { topic: "events", type: "single",
    q: "How long is the Daily Scrum?",
    options: ["15 minutes", "30 minutes", "It depends on the Sprint length", "Up to 1 hour"],
    answer: [0],
    exp: "The Daily Scrum is a 15-minute event for the Developers, regardless of the Sprint length." },
  { topic: "fundamentals", type: "tf",
    q: "A Scrum Team is typically 10 or fewer people.",
    options: ["True", "False"],
    answer: [0],
    exp: "The Scrum Guide states that the Scrum Team is typically 10 or fewer people." },
  { topic: "fundamentals", type: "single",
    q: "Who is committed to creating a usable Increment each Sprint?",
    options: ["The Product Owner", "The Scrum Master", "The Developers", "The stakeholders"],
    answer: [2],
    exp: "The Developers are committed to creating any aspect of a usable Increment each Sprint." },
  { topic: "fundamentals", type: "single",
    q: "Who is responsible for all product-related activities, such as stakeholder collaboration, verification, operation, and research?",
    options: ["Only the Product Owner", "Only the Developers", "The Scrum Team", "Management"],
    answer: [2],
    exp: "The entire Scrum Team is responsible for all product-related activities." },
  { topic: "fundamentals", type: "tf",
    q: "Within a Scrum Team, there are sub-teams and hierarchies to organize the work.",
    options: ["True", "False"],
    answer: [1],
    exp: "There are no sub-teams or hierarchies within a Scrum Team. It is a cohesive unit focused on one objective at a time." },
  { topic: "events", type: "single",
    q: "Who can cancel a Sprint?",
    options: ["The Scrum Master", "The Developers", "The Product Owner", "The stakeholders"],
    answer: [2],
    exp: "Only the Product Owner has the authority to cancel the Sprint, which may make sense if the Sprint Goal becomes obsolete." },
  { topic: "events", type: "single",
    q: "When should a Sprint be cancelled?",
    options: ["When the team will not complete all the items", "When the Sprint Goal becomes obsolete", "When a stakeholder asks for it", "When a Developer goes on vacation"],
    answer: [1],
    exp: "A Sprint could be cancelled if the Sprint Goal becomes obsolete." },
  { topic: "fundamentals", type: "tf",
    q: "If multiple Scrum Teams work on the same product, they should share the same Product Backlog and the same Product Owner.",
    options: ["True", "False"],
    answer: [0],
    exp: "Multiple Scrum Teams working on the same product share the same Product Goal, Product Backlog, and Product Owner." },
  { topic: "po", type: "single",
    q: "What is the Product Owner accountable for?",
    options: ["Maximizing the value of the product resulting from the work of the Scrum Team", "Managing the Developers' tasks", "Ensuring the Daily Scrum takes place", "Setting the estimates for items"],
    answer: [0],
    exp: "The Product Owner is accountable for maximizing the value of the product resulting from the work of the Scrum Team." },
  { topic: "po", type: "tf",
    q: "The Product Owner is one person, not a committee.",
    options: ["True", "False"],
    answer: [0],
    exp: "The Product Owner is one person. The Product Owner may represent the needs of many stakeholders in the Product Backlog." },
  { topic: "po", type: "multi",
    q: "Which activities are part of the Product Owner's effective Product Backlog management? (Choose 4)",
    options: ["Developing and explicitly communicating the Product Goal", "Creating and clearly communicating Product Backlog items", "Ordering Product Backlog items", "Ensuring that the Product Backlog is transparent, visible, and understood", "Assigning tasks to each Developer"],
    answer: [0, 1, 2, 3],
    exp: "These are the four activities listed in the Scrum Guide. Assigning tasks is not the Product Owner's role: the Developers are self-managing." },
  { topic: "po", type: "tf",
    q: "The Product Owner may delegate the work of managing the Product Backlog to others, but remains accountable.",
    options: ["True", "False"],
    answer: [0],
    exp: "The Product Owner may do the work or delegate it to others, but remains accountable." },
  { topic: "po", type: "single",
    q: "A stakeholder wants to change the priority of a Product Backlog item. What should they do?",
    options: ["Ask the Developers directly", "Convince the Product Owner", "Ask the Scrum Master to change the order", "Change the Product Backlog themselves"],
    answer: [1],
    exp: "Those wanting to change the Product Backlog can do so by trying to convince the Product Owner." },
  { topic: "po", type: "single",
    q: "For the Product Owner to succeed, what must the entire organization do?",
    options: ["Approve each of their decisions in a committee", "Respect their decisions", "Appoint a manager to supervise them", "Allow them to work only part-time"],
    answer: [1],
    exp: "For Product Owners to succeed, the entire organization must respect their decisions, which are visible in the content and ordering of the Product Backlog." },
  { topic: "po", type: "multi",
    q: "Which of these are ways for the Product Owner to increase the value delivered? (Choose 2)",
    options: ["Ordering the Product Backlog to deliver the most valuable items first", "Collaborating with stakeholders and users to validate hypotheses", "Requiring the Developers to work overtime", "Skipping the Sprint Review to save time"],
    answer: [0, 1],
    exp: "Ordering by value and validating hypotheses with users increase value. Overtime and eliminating events reduce transparency and sustainability." },
  { topic: "po", type: "tf",
    q: "The Product Owner must attend the Daily Scrum.",
    options: ["True", "False"],
    answer: [1],
    exp: "The Daily Scrum is for the Developers. The Product Owner and Scrum Master participate as Developers only if they are actively working on items in the Sprint Backlog." },
  { topic: "po", type: "single",
    q: "What best describes the Product Owner's role regarding the product vision?",
    options: ["Receives a ready-made vision and simply passes it on", "Develops and communicates the Product Goal aligned with the vision", "Has no relationship with the vision", "Documents the vision only at the start of the project"],
    answer: [1],
    exp: "The Product Owner is accountable for developing and explicitly communicating the Product Goal, which gives the Scrum Team direction." },
  { topic: "po", type: "single",
    q: "A Product Owner struggles to be heard by the organization, and their decisions are frequently overturned. Who should help?",
    options: ["The Developers, by taking over the decisions", "The Scrum Master, by serving the organization and the Product Owner", "No one. The Product Owner must solve it alone", "The main customer, by replacing the Product Owner"],
    answer: [1],
    exp: "The Scrum Master serves the organization and the Product Owner, helping remove impediments and promoting an understanding of Scrum." },
  { topic: "po", type: "tf",
    q: "The Product Owner can also be a Developer on the same Scrum Team.",
    options: ["True", "False"],
    answer: [0],
    exp: "The Scrum Guide does not prohibit it. If the Product Owner actively works on Sprint Backlog items, they also act as a Developer, but should be aware of the conflict in focus." },
  { topic: "po", type: "single",
    q: "What is the primary measure of a Product Owner's success?",
    options: ["Number of items delivered", "Team velocity", "Value delivered and outcomes achieved", "Adherence to the initial plan"],
    answer: [2],
    exp: "Success is measured by value and outcomes, not by output or adherence to a plan." },
  { topic: "backlog", type: "single",
    q: "What is the Product Backlog?",
    options: ["A fixed list of requirements approved at the start", "An emergent, ordered list of what is needed to improve the product", "A list of technical tasks for the Sprint", "The project plan with dates"],
    answer: [1],
    exp: "The Product Backlog is an emergent, ordered list of what is needed to improve the product. It is the single source of work undertaken by the Scrum Team." },
  { topic: "backlog", type: "tf",
    q: "The Product Backlog is the single source of work undertaken by the Scrum Team.",
    options: ["True", "False"],
    answer: [0],
    exp: "The Scrum Guide defines the Product Backlog as the single source of work undertaken by the Scrum Team." },
  { topic: "backlog", type: "single",
    q: "What is Product Backlog refinement?",
    options: ["A formal event with a 2-hour timebox", "The ongoing activity of breaking down and further defining items into smaller, more precise items", "The approval of items by the stakeholders", "The meeting where the Product Owner presents the final prioritization"],
    answer: [1],
    exp: "Refinement is an ongoing activity (not an event) of breaking down and further defining items, adding details such as a description, order, and size." },
  { topic: "backlog", type: "single",
    q: "Who is responsible for sizing (estimating) Product Backlog items?",
    options: ["The Product Owner", "The Scrum Master", "The Developers who will be doing the work", "The stakeholders"],
    answer: [2],
    exp: "The Developers who will be doing the work are responsible for the sizing. The Product Owner may influence them by helping them understand and select trade-offs." },
  { topic: "backlog", type: "tf",
    q: "All Product Backlog items must be fully detailed before they are added to the backlog.",
    options: ["True", "False"],
    answer: [1],
    exp: "Items at the top tend to be more refined, while items lower down may be vague. The level of detail is proportional to how soon they will be worked on." },
  { topic: "backlog", type: "single",
    q: "When is a Product Backlog item considered ready for selection in Sprint Planning?",
    options: ["When the Product Owner has signed off the requirements document", "When it can be Done by the Scrum Team within one Sprint", "When all the stakeholders have approved it", "When the Scrum Master has assigned story points to it"],
    answer: [1],
    exp: "Product Backlog items that can be Done by the Scrum Team within one Sprint are deemed ready for selection in a Sprint Planning event." },
  { topic: "backlog", type: "multi",
    q: "Which attributes do Product Backlog items usually have after refinement? (Choose 3)",
    options: ["Description", "Order", "Size", "Name of the responsible Developer", "Formal customer approval"],
    answer: [0, 1, 2],
    exp: "Refinement adds details such as a description, order, and size. Attributes often vary with the domain of work." },
  { topic: "backlog", type: "tf",
    q: "The Product Backlog should be ordered strictly by business value, without considering risk or dependencies.",
    options: ["True", "False"],
    answer: [1],
    exp: "The Product Owner decides the order considering value, risk, dependencies, learning, and other factors. There is no single rule." },
  { topic: "backlog", type: "single",
    q: "A Product Backlog with hundreds of highly detailed items covering the next two years is a sign of what?",
    options: ["Excellent planning", "Possible waste and lack of adaptation", "A mandatory Scrum requirement", "Team maturity"],
    answer: [1],
    exp: "Over-detailing distant items creates waste, because they will probably change. The Product Backlog is emergent." },
  { topic: "backlog", type: "tf",
    q: "Product Backlog items must be written in the User Story format.",
    options: ["True", "False"],
    answer: [1],
    exp: "Scrum does not require User Stories. They are an optional complementary practice." },
  { topic: "backlog", type: "single",
    q: "What is the purpose of the Product Goal?",
    options: ["To list all the features to be delivered", "To describe a future state of the product that serves as a target for the Scrum Team", "To define the budget", "To set fixed delivery deadlines"],
    answer: [1],
    exp: "The Product Goal describes a future state of the product and is the long-term objective for the Scrum Team." },
  { topic: "backlog", type: "tf",
    q: "The Scrum Team must fulfill (or abandon) one Product Goal before taking on the next.",
    options: ["True", "False"],
    answer: [0],
    exp: "The Scrum Team must fulfill or abandon one objective before taking on the next." },
  { topic: "backlog", type: "single",
    q: "Who can add items to the Product Backlog?",
    options: ["Only the Product Owner", "Anyone, as long as the Product Owner remains accountable for its content and ordering", "Only the stakeholders", "Only the Scrum Master"],
    answer: [1],
    exp: "Others may contribute items, but the Product Owner remains accountable for the Product Backlog." },
  { topic: "backlog", type: "multi",
    q: "Which of the following can be part of the Product Backlog? (Choose 3)",
    options: ["New features", "Bug fixes", "Technical and infrastructure improvements", "Board meeting minutes"],
    answer: [0, 1, 2],
    exp: "The Product Backlog contains everything needed to improve the product: features, fixes, technical work, experiments, etc." },
  { topic: "backlog", type: "single",
    q: "How much of the Scrum Team's time should be spent on Product Backlog refinement?",
    options: ["Exactly 10% of the Sprint", "There is no set amount; the team decides as needed", "One day per Sprint", "None, it is exclusively the Product Owner's work"],
    answer: [1],
    exp: "The 2020 Scrum Guide does not define a percentage. The Scrum Team decides how much refinement is needed." },
  { topic: "value", type: "single",
    q: "What is the best definition of a 'product' according to the Scrum Guide?",
    options: ["Software delivered to the customer", "A vehicle to deliver value, with a clear boundary, known stakeholders, and well-defined users", "Any document produced by the team", "A list of features"],
    answer: [1],
    exp: "A product is a vehicle to deliver value. It has a clear boundary, known stakeholders, and well-defined users. It could be a service, a physical product, or something more abstract." },
  { topic: "value", type: "single",
    q: "What is the difference between output and outcome?",
    options: ["They are synonyms", "Output is what is produced; outcome is the resulting change in behavior or result achieved", "Outcome is the number of features; output is the profit", "Output is measured by the customer; outcome by the team"],
    answer: [1],
    exp: "Output = what we deliver (features). Outcome = the result achieved for users and the organization. The Product Owner focuses on outcomes." },
  { topic: "value", type: "tf",
    q: "Velocity is a good metric for measuring the value delivered to the customer.",
    options: ["True", "False"],
    answer: [1],
    exp: "Velocity measures capacity and output, not value. Value is measured by outcomes such as satisfaction, revenue, and usage." },
  { topic: "value", type: "multi",
    q: "Which are value indicators a Product Owner can track? (Choose 3)",
    options: ["Customer satisfaction", "Revenue per employee", "Feature usage rate", "Number of hours worked", "Lines of code"],
    answer: [0, 1, 2],
    exp: "Satisfaction, revenue, and usage indicate value. Hours and lines of code measure effort, not value." },
  { topic: "value", type: "single",
    q: "Evidence-Based Management (EBM) organizes the measurement of value into which Key Value Areas?",
    options: ["Cost, Schedule, Scope, and Quality", "Current Value, Unrealized Value, Ability to Innovate, and Time to Market", "Velocity, Burndown, Bugs, and Hours", "Revenue, Profit, Shares, and Dividends"],
    answer: [1],
    exp: "EBM uses four Key Value Areas: Current Value, Unrealized Value, Ability to Innovate, and Time to Market." },
  { topic: "value", type: "single",
    q: "In EBM, what does Unrealized Value measure?",
    options: ["The value delivered today", "The potential value that could be realized by better meeting market needs", "The maintenance cost", "The time between idea and delivery"],
    answer: [1],
    exp: "Unrealized Value represents the potential future value the organization could capture." },
  { topic: "value", type: "single",
    q: "In EBM, which factor negatively affects the Ability to Innovate?",
    options: ["High technical debt", "Frequent user feedback", "Frequent releases", "Cross-functional teams"],
    answer: [0],
    exp: "Technical debt consumes capacity that could go toward innovation, reducing the Ability to Innovate." },
  { topic: "value", type: "tf",
    q: "Delivering more features always creates more value.",
    options: ["True", "False"],
    answer: [1],
    exp: "Many features are rarely or never used. Value comes from solving real problems, not from the volume of output." },
  { topic: "release", type: "single",
    q: "Why does releasing Increments frequently help maximize value?",
    options: ["Because it pleases management", "Because it generates fast market feedback and reduces risk", "Because Scrum requires one release per Sprint", "Because it reduces the need for testing"],
    answer: [1],
    exp: "Frequent releases allow hypotheses to be validated early, enabling learning and adaptation, and reducing the risk of building the wrong thing." },
  { topic: "release", type: "tf",
    q: "In Scrum, an Increment can only be released at the end of the Sprint, after the Sprint Review.",
    options: ["True", "False"],
    answer: [1],
    exp: "An Increment may be delivered to stakeholders prior to the end of the Sprint. The Sprint Review should never be considered a gate to releasing value." },
  { topic: "value", type: "single",
    q: "What does Time to Market mean in EBM?",
    options: ["The duration of the project", "The ability to quickly deliver new capabilities, services, or products", "The time until the product becomes profitable", "The time spent on marketing"],
    answer: [1],
    exp: "Time to Market expresses the organization's ability to quickly deliver new capabilities and learn from feedback." },
  { topic: "value", type: "single",
    q: "A product already has high customer satisfaction and dominates its market, but technical debt is high. What is the greatest risk?",
    options: ["There is no risk", "Future loss of the ability to innovate and respond to the market", "An immediate increase in revenue", "Too much feedback"],
    answer: [1],
    exp: "With high technical debt, Ability to Innovate and Time to Market decline, threatening future value." },
  { topic: "value", type: "multi",
    q: "Which practices help validate whether a product idea creates value before building it completely? (Choose 2)",
    options: ["Building an experiment or MVP", "Testing the hypothesis with real users", "Documenting everything before starting", "Waiting for annual budget approval"],
    answer: [0, 1],
    exp: "Experiments, MVPs, and user testing validate hypotheses at low cost and enable fast learning." },
  { topic: "events", type: "single",
    q: "What is the main event for inspecting the outcome of the Sprint with stakeholders?",
    options: ["Sprint Planning", "Daily Scrum", "Sprint Review", "Sprint Retrospective"],
    answer: [2],
    exp: "At the Sprint Review, the Scrum Team and stakeholders inspect the outcome of the Sprint and determine future adaptations." },
  { topic: "events", type: "tf",
    q: "The Sprint Review should be treated as a formal presentation, with slides, for stakeholder approval.",
    options: ["True", "False"],
    answer: [1],
    exp: "The Sprint Review is a collaborative working session, not merely a presentation." },
  { topic: "po", type: "single",
    q: "During the Sprint, a stakeholder asks a Developer directly for a new feature. What should happen?",
    options: ["The Developer implements it immediately", "The request is directed to the Product Owner, who evaluates it and orders it in the Product Backlog", "The Scrum Master rejects the request", "The Sprint is cancelled"],
    answer: [1],
    exp: "New requests go through the Product Owner, who decides whether and where the item goes in the Product Backlog." },
  { topic: "po", type: "multi",
    q: "Which of these are good Product Owner practices for engaging stakeholders? (Choose 3)",
    options: ["Inviting them to the Sprint Review", "Keeping the Product Backlog transparent and accessible", "Collaborating continuously to understand their needs", "Hiding the Product Backlog to avoid pressure", "Accepting all requests without analysis"],
    answer: [0, 1, 2],
    exp: "Transparency and continuous collaboration are essential. Hiding the Product Backlog or accepting everything without analysis harms value." },
  { topic: "po", type: "tf",
    q: "The Product Owner is the only permitted point of contact between the Scrum Team and stakeholders.",
    options: ["True", "False"],
    answer: [1],
    exp: "Developers can and should interact with stakeholders and users. The Product Owner remains accountable for the Product Backlog." },
  { topic: "po", type: "single",
    q: "Two important stakeholders request conflicting features. What should the Product Owner do?",
    options: ["Build both", "Make the decision based on value and the Product Goal, communicating it transparently", "Let the Scrum Master decide", "Ask the Developers to vote"],
    answer: [1],
    exp: "The Product Owner decides based on value, the Product Goal, and evidence, explaining the decision transparently." },
  { topic: "events", type: "single",
    q: "What is an expected result of the Sprint Review?",
    options: ["A revised Product Backlog with probable items for the next Sprint", "A process improvement plan", "The customer's signed acceptance", "The task list for the next Sprint"],
    answer: [0],
    exp: "The result of the Sprint Review is a revised Product Backlog that defines the probable items for the next Sprint." },
  { topic: "events", type: "multi",
    q: "Which topics can be discussed at the Sprint Review? (Choose 3)",
    options: ["What was accomplished in the Sprint", "Changes in the environment or market", "What to do next to optimize value", "Individual performance appraisals of the Developers"],
    answer: [0, 1, 2],
    exp: "The Sprint Review inspects what was done and what has changed, and decides on next steps. Individual appraisals are not part of it." },
  { topic: "events", type: "tf",
    q: "The Sprint Retrospective is the main event for the Scrum Team to collaborate with stakeholders about the product.",
    options: ["True", "False"],
    answer: [1],
    exp: "The Sprint Retrospective belongs to the Scrum Team and focuses on quality and effectiveness. Collaboration with stakeholders about the product happens mainly at the Sprint Review." },
  { topic: "po", type: "single",
    q: "What is the most appropriate distinction between a customer and a user?",
    options: ["They are always the same person", "The customer pays or decides to buy; the user uses the product, and they may be different people", "The user is internal, the customer is external", "There is no relevant difference for the Product Owner"],
    answer: [1],
    exp: "Customers and users may be different. The Product Owner needs to understand the needs of both." },
  { topic: "events", type: "multi",
    q: "Which topics are addressed in Sprint Planning? (Choose 3)",
    options: ["Why is this Sprint valuable?", "What can be Done this Sprint?", "How will the chosen work get done?", "Who will be evaluated at the end?"],
    answer: [0, 1, 2],
    exp: "Sprint Planning addresses three topics: Why (the Sprint Goal), What, and How." },
  { topic: "events", type: "single",
    q: "Who defines the Sprint Goal?",
    options: ["Only the Product Owner", "The entire Scrum Team, collaboratively", "The Scrum Master", "The stakeholders"],
    answer: [1],
    exp: "The Product Owner proposes how the product could increase its value, and the whole Scrum Team collaborates to define the Sprint Goal." },
  { topic: "release", type: "single",
    q: "Who selects how many Product Backlog items are included in the Sprint?",
    options: ["The Product Owner", "The Developers", "The Scrum Master", "Management"],
    answer: [1],
    exp: "The Developers select items from the Product Backlog, through discussion with the Product Owner, considering their capacity and past performance." },
  { topic: "events", type: "single",
    q: "Who owns the Sprint Backlog?",
    options: ["The Product Owner", "The Scrum Master", "The Developers", "The stakeholders"],
    answer: [2],
    exp: "The Sprint Backlog is a plan by and for the Developers." },
  { topic: "events", type: "tf",
    q: "During the Sprint, scope may be clarified and renegotiated with the Product Owner as more is learned.",
    options: ["True", "False"],
    answer: [0],
    exp: "Scope may be clarified and renegotiated with the Product Owner, as long as the Sprint Goal is not endangered." },
  { topic: "events", type: "tf",
    q: "During the Sprint, changes that would endanger the Sprint Goal may be made if a stakeholder requests them.",
    options: ["True", "False"],
    answer: [1],
    exp: "No changes are made during the Sprint that would endanger the Sprint Goal." },
  { topic: "release", type: "multi",
    q: "Which practices can be used to forecast progress toward a goal? (Choose 3)",
    options: ["Burn-downs", "Burn-ups", "Cumulative flows", "Gantt charts with mandatory fixed dates"],
    answer: [0, 1, 2],
    exp: "The Scrum Guide mentions burn-downs, burn-ups, and cumulative flows as useful practices, but notes that they do not replace the importance of empiricism." },
  { topic: "release", type: "tf",
    q: "Forecasting practices such as burn-downs eliminate uncertainty about the future.",
    options: ["True", "False"],
    answer: [1],
    exp: "These practices are useful, but they do not replace empiricism. In complex environments, what will happen is unknown; only what has already happened may be used for forward-looking decision making." },
  { topic: "release", type: "single",
    q: "How often should progress toward the Product Goal be inspected?",
    options: ["Only at the end of the project", "At least at the Sprint Review", "Only when management asks", "Once a year"],
    answer: [1],
    exp: "Progress toward the Product Goal is inspected and adapted at least at the Sprint Review." },
  { topic: "release", type: "single",
    q: "A company asks the Product Owner for the exact date when all of the current scope will be done. What is the best response?",
    options: ["Give a fixed date and guarantee it will be met", "Provide a forecast based on empirical data, updating it as more is learned", "Refuse to answer", "Ask the Scrum Master to set it"],
    answer: [1],
    exp: "The Product Owner can offer forecasts based on past performance, making it clear that they evolve as new information emerges." },
  { topic: "release", type: "tf",
    q: "The budget for a product developed with Scrum can be reviewed every Sprint based on the value delivered.",
    options: ["True", "False"],
    answer: [0],
    exp: "Since every Sprint delivers an Increment, the organization can decide to continue, adjust, or stop the investment each cycle." },
  { topic: "events", type: "single",
    q: "What is the role of the Product Owner in Sprint Planning?",
    options: ["Ensuring attendees are prepared to discuss the most important items and how they map to the Product Goal", "Deciding how many items the Developers must do", "Creating the technical plan for the Sprint", "Only observing"],
    answer: [0],
    exp: "The Product Owner ensures that attendees are prepared to discuss the most important Product Backlog items and how they map to the Product Goal." },
  { topic: "release", type: "single",
    q: "What is the Definition of Done?",
    options: ["A task list for each item", "A formal description of the state of the Increment when it meets the quality measures required for the product", "The customer's acceptance", "The acceptance criteria of each User Story"],
    answer: [1],
    exp: "The Definition of Done is a formal description of the state of the Increment when it meets the quality measures required for the product." },
  { topic: "release", type: "tf",
    q: "If a Product Backlog item does not meet the Definition of Done, it can be presented at the Sprint Review as partially complete.",
    options: ["True", "False"],
    answer: [1],
    exp: "If it does not meet the Definition of Done, the item cannot be released or even presented at the Sprint Review. Instead, it returns to the Product Backlog for future consideration." },
  { topic: "release", type: "single",
    q: "If the Definition of Done is part of the organization's standards, what should the Scrum Team do?",
    options: ["Ignore it and create its own", "Follow it as a minimum", "Request an exemption", "Use it only in the final Sprints"],
    answer: [1],
    exp: "If the organization has a standard, all Scrum Teams must follow it as a minimum. If not, the Scrum Team must create a Definition of Done appropriate for the product." },
  { topic: "release", type: "single",
    q: "Multiple Scrum Teams are working on the same product. What should the Definition of Done be?",
    options: ["Each team defines its own, independently", "They must mutually define and comply with the same Definition of Done", "Only the first team defines it", "It does not need to exist"],
    answer: [1],
    exp: "If there are multiple Scrum Teams working together on a product, they must mutually define and comply with the same Definition of Done." },
  { topic: "release", type: "tf",
    q: "Decreasing quality is an acceptable way to meet the Sprint Goal when time is tight.",
    options: ["True", "False"],
    answer: [1],
    exp: "During the Sprint, quality does not decrease." },
  { topic: "release", type: "single",
    q: "What is the consequence of accumulating technical debt for the Product Owner?",
    options: ["Greater speed in the long term", "Less transparency about the actual state of the product and reduced future value", "None, it is the Developers' responsibility", "An automatic increase in quality"],
    answer: [1],
    exp: "Technical debt reduces transparency, slows down future delivery, and decreases the ability to innovate. This directly impacts value." },
  { topic: "release", type: "tf",
    q: "An Increment must be usable, even if the Product Owner decides not to release it.",
    options: ["True", "False"],
    answer: [0],
    exp: "Every Increment must be usable. The decision to release is separate from the determination that it is Done." },
  { topic: "release", type: "single",
    q: "Can multiple Increments be created within a Sprint?",
    options: ["No, only one at the end", "Yes, and their sum is presented at the Sprint Review", "Only with management authorization", "Only in one-month Sprints"],
    answer: [1],
    exp: "Multiple Increments may be created within a Sprint. Their sum is presented at the Sprint Review, but they may be delivered earlier." },
  { topic: "events", type: "single",
    q: "What is the purpose of the Sprint Retrospective?",
    options: ["To inspect the Increment with stakeholders", "To plan ways to increase quality and effectiveness", "To update the Product Backlog", "To evaluate the Product Owner's performance"],
    answer: [1],
    exp: "The purpose of the Sprint Retrospective is to plan ways to increase quality and effectiveness." },
  { topic: "events", type: "single",
    q: "What is the purpose of the Daily Scrum?",
    options: ["To report status to the Product Owner", "To inspect progress toward the Sprint Goal and adapt the Sprint Backlog", "To solve all technical problems", "To assign tasks to the Developers"],
    answer: [1],
    exp: "The Daily Scrum is used to inspect progress toward the Sprint Goal and adapt the Sprint Backlog as necessary." },
  { topic: "events", type: "tf",
    q: "The Developers can select whatever structure and techniques they want for the Daily Scrum, as long as it focuses on progress toward the Sprint Goal.",
    options: ["True", "False"],
    answer: [0],
    exp: "The 2020 Scrum Guide removed the three mandatory questions. The Developers choose the structure." },
  { topic: "fundamentals", type: "single",
    q: "Which term does the 2020 Scrum Guide use to describe that the Scrum Team internally decides who does what, when, and how?",
    options: ["Self-organizing", "Self-managing", "Autocratic", "Fully autonomous"],
    answer: [1],
    exp: "The 2020 Scrum Guide describes Scrum Teams as self-managing." },
  { topic: "fundamentals", type: "multi",
    q: "How does the Scrum Master serve the Product Owner? (Choose 3)",
    options: ["Helping find techniques for effective Product Goal definition and Product Backlog management", "Helping the Scrum Team understand the need for clear and concise Product Backlog items", "Facilitating stakeholder collaboration as requested or needed", "Ordering the Product Backlog on behalf of the Product Owner"],
    answer: [0, 1, 2],
    exp: "The Scrum Master supports the Product Owner with techniques, understanding and facilitation, but does not make product decisions." },
  { topic: "events", type: "tf",
    q: "Scrum events are designed to create regularity and to minimize the need for meetings not defined in Scrum.",
    options: ["True", "False"],
    answer: [0],
    exp: "Events create regularity and reduce extra meetings; ideally they are held at the same time and place." },
  { topic: "events", type: "single",
    q: "What happens to the completed Sprint Backlog items when a Sprint is cancelled?",
    options: ["They are discarded", "The Product Owner reviews them; if they are usable, they can be accepted", "They are automatically released", "They must go back to the top of the Product Backlog"],
    answer: [1],
    exp: "Completed items are reviewed, and the Product Owner may accept those that are usable. Incomplete items are re-estimated and returned to the Product Backlog." },
  { topic: "events", type: "tf",
    q: "The Sprint Review is the last event of the Sprint.",
    options: ["True", "False"],
    answer: [1],
    exp: "The Sprint Retrospective is the last event of the Sprint." },
  { topic: "po", type: "single",
    q: "An organization wants to appoint three people as Product Owners for the same product, each owning part of the Product Backlog. What does Scrum recommend?",
    options: ["Proceed with three Product Owners, one per team", "Have a single Product Owner for the product, who may be supported by others", "Form a product committee", "Eliminate the Product Owner role"],
    answer: [1],
    exp: "A product has one Product Owner and one Product Backlog. Others can help, but accountability remains with one person." },
  { topic: "po", type: "multi",
    q: "Which characteristics help a Product Owner be effective? (Choose 3)",
    options: ["Having the authority to make product decisions", "Knowing the domain and the market", "Being available to the Scrum Team and stakeholders", "Controlling how the Developers do the technical work"],
    answer: [0, 1, 2],
    exp: "Authority, domain knowledge and availability are essential. The Developers decide how to do the work." },
  { topic: "value", type: "single",
    q: "A Product Owner notices that a feature released three months ago is barely used. What is the best course of action?",
    options: ["Ignore it, since it has already been delivered", "Investigate why using data and users, then decide whether to improve, remove, or keep it", "Request more similar features", "Blame the Developers"],
    answer: [1],
    exp: "The Product Owner uses evidence to make decisions. Rarely used features add maintenance cost and can be improved or removed." },
  { topic: "po", type: "single",
    q: "How can the Product Owner make transparent to the organization what the Scrum Team will work on next?",
    options: ["Through a visible, ordered and understandable Product Backlog", "By sending timesheet reports", "Through mandatory weekly status meetings", "By keeping a private spreadsheet"],
    answer: [0],
    exp: "A transparent Product Backlog shows everyone what the Scrum Team will work on and in what order." },
  { topic: "events", type: "tf",
    q: "A Sprint can be extended if the team cannot finish the planned items.",
    options: ["True", "False"],
    answer: [1],
    exp: "Sprints have a fixed length. A Sprint is never extended; unfinished items return to the Product Backlog." },
  { topic: "events", type: "single",
    q: "What is the effect of Sprints that are too long?",
    options: ["Lower complexity and lower risk", "The Sprint Goal may become invalid, and complexity and risk may rise", "More frequent feedback", "No effect"],
    answer: [1],
    exp: "When a Sprint's horizon is too long, the Sprint Goal may become invalid, and complexity and risk may rise." },
  { topic: "release", type: "tf",
    q: "Acceptance criteria for an item replace the Definition of Done.",
    options: ["True", "False"],
    answer: [1],
    exp: "Acceptance criteria are specific to each item. The Definition of Done applies to the entire Increment. The two complement each other." },
  { topic: "backlog", type: "multi",
    q: "Which factors can the Product Owner consider when ordering the Product Backlog? (Choose 4)",
    options: ["Business value", "Risk", "Dependencies", "Return on investment (ROI)", "A Developer's personal preference"],
    answer: [0, 1, 2, 3],
    exp: "Ordering considers value, risk, dependencies, ROI, learning and any other factors the Product Owner deems relevant to maximizing value." },
  { topic: "backlog", type: "single",
    q: "Two items have similar business value. Item A has high technical risk and item B is simple. What could justify placing item A first?",
    options: ["Nothing; simple items always come first", "Reducing risk early, learning before the cost of change increases", "Keeping the Developers busy", "Pleasing management"],
    answer: [1],
    exp: "Addressing risk early generates learning and reduces uncertainty. Risk is a legitimate ordering factor." },
  { topic: "backlog", type: "tf",
    q: "The Product Owner can reorder the Product Backlog at any time, including during the Sprint.",
    options: ["True", "False"],
    answer: [0],
    exp: "The Product Backlog is dynamic. The Product Owner can reorder it at any time. What does not change during the Sprint is the Sprint Goal." },
  { topic: "backlog", type: "single",
    q: "Who decides the final order of the Product Backlog items?",
    options: ["The stakeholders, by vote", "The Product Owner", "The Developers", "The Scrum Master"],
    answer: [1],
    exp: "The Product Owner is solely accountable for ordering the Product Backlog. Others may influence it, but the decision is the Product Owner's." },
  { topic: "backlog", type: "single",
    q: "Who participates in Product Backlog refinement?",
    options: ["Only the Product Owner", "The Product Owner and the Developers, possibly including stakeholders", "Only the Developers", "Only the Scrum Master"],
    answer: [1],
    exp: "Refinement is collaborative: the Product Owner and Developers work together, and stakeholders may contribute when useful." },
  { topic: "backlog", type: "tf",
    q: "Product Backlog refinement is an official Scrum event with a defined timebox.",
    options: ["True", "False"],
    answer: [1],
    exp: "Refinement is an ongoing activity, not an event. A common guideline is up to 10% of the team's capacity, but that is not a rule in the 2020 Scrum Guide." },
  { topic: "backlog", type: "single",
    q: "What is the main purpose of refinement?",
    options: ["To ensure the top items are ready for Sprint Planning", "To formally approve requirements", "To assign items to each Developer", "To calculate the project budget"],
    answer: [0],
    exp: "Refinement breaks down and adds detail to items so that those at the top are ready to be selected in Sprint Planning." },
  { topic: "backlog", type: "single",
    q: "At Sprint Planning, the Developers do not understand the top Product Backlog items well. What is the most likely cause?",
    options: ["Insufficient refinement before Sprint Planning", "Sprints that are too long", "Too many Daily Scrums", "An overly strict Definition of Done"],
    answer: [0],
    exp: "Poorly understood items at Sprint Planning usually indicate that ongoing refinement was not sufficient." },
  { topic: "backlog", type: "multi",
    q: "What makes a Product Backlog transparent? (Choose 3)",
    options: ["Being visible to everyone interested", "Being understood by the Scrum Team and stakeholders", "Reflecting the actual order of what will be done", "Being accessible only to the Product Owner"],
    answer: [0, 1, 2],
    exp: "Transparency requires visibility, shared understanding and an accurate reflection of reality. Hiding the Product Backlog undermines empiricism." },
  { topic: "backlog", type: "tf",
    q: "The Product Backlog is never complete and evolves as the product and the market change.",
    options: ["True", "False"],
    answer: [0],
    exp: "The Product Backlog is emergent: it constantly changes to reflect what the product needs to be valuable." },
  { topic: "backlog", type: "single",
    q: "An item at the bottom of the Product Backlog has not been prioritized for over a year. What should the Product Owner consider?",
    options: ["Keeping it forever", "Assessing whether it still makes sense and removing it if it does not deliver value", "Moving it to the top so it is not forgotten", "Asking the Scrum Master to decide"],
    answer: [1],
    exp: "Removing items that do not deliver value keeps the Product Backlog lean and transparent. This is part of Product Backlog management." },
  { topic: "backlog", type: "single",
    q: "How can the Product Owner influence the estimates made by the Developers?",
    options: ["By imposing a number", "By helping them understand the items and select trade-offs", "They cannot influence them in any way", "By asking the Scrum Master to review them"],
    answer: [1],
    exp: "The Product Owner influences estimates by helping the Developers understand the item and the trade-offs, but the Developers who will do the work are the ones who estimate." },
  { topic: "backlog", type: "tf",
    q: "The Product Backlog should be ordered by the order in which stakeholder requests arrive.",
    options: ["True", "False"],
    answer: [1],
    exp: "The Product Backlog is ordered to maximize value, not by arrival order or by stakeholder." },
  { topic: "backlog", type: "single",
    q: "A large, vague item is near the top of the Product Backlog. What is the best course of action?",
    options: ["Pull it into the Sprint as is", "Refine it, breaking it down into smaller items that fit within a Sprint", "Move it to the bottom", "Delete it"],
    answer: [1],
    exp: "Items that are close to being worked on should be refined into smaller pieces that fit within a Sprint." },
  { topic: "value", type: "single",
    q: "What is the relationship between the product vision and the Product Goal?",
    options: ["They are the same thing", "The vision provides purpose and long-term direction; the Product Goal is a concrete target toward that vision", "The Product Goal replaces the vision", "The vision is defined by the Developers"],
    answer: [1],
    exp: "The vision describes the product's purpose. The Product Goal is a long-term objective that moves the product in that direction." },
  { topic: "value", type: "tf",
    q: "The Product Goal is in the Product Backlog.",
    options: ["True", "False"],
    answer: [0],
    exp: "The Product Goal is in the Product Backlog. The rest of the Product Backlog emerges to define what will fulfill the Product Goal." },
  { topic: "value", type: "multi",
    q: "Which characteristics make a product vision effective? (Choose 3)",
    options: ["Clear and easy to communicate", "Focused on the customer's problem and on value", "Inspiring to the team and stakeholders", "A detailed list of features"],
    answer: [0, 1, 2],
    exp: "A good vision is clear, centered on customer value, and inspiring. A feature list is not a vision." },
  { topic: "value", type: "single",
    q: "The Product Goal has been achieved. What happens next?",
    options: ["The Scrum Team must be disbanded", "The Product Owner defines a new Product Goal, if there is still value to deliver", "The Sprint is cancelled", "The product is frozen"],
    answer: [1],
    exp: "Once the Product Goal is fulfilled, the Product Owner can define the next one, always seeking to maximize value." },
  { topic: "value", type: "single",
    q: "What is the main focus of Evidence-Based Management (EBM)?",
    options: ["Measuring individual productivity", "Using evidence to measure and improve the value delivered", "Controlling deadlines and budget", "Comparing teams against each other"],
    answer: [1],
    exp: "EBM helps organizations measure value with evidence and improve their ability to deliver it." },
  { topic: "value", type: "single",
    q: "In EBM, what does Current Value measure?",
    options: ["Potential future value", "The value the product delivers today to customers and the organization", "Delivery time", "Technical debt"],
    answer: [1],
    exp: "Current Value measures the value delivered today, such as customer and employee satisfaction and revenue." },
  { topic: "events", type: "single",
    q: "In Sprint Planning, what is the main contribution expected from the Product Owner?",
    options: ["Explaining how the product could increase its value in the Sprint and discussing the top Product Backlog items", "Breaking items down into technical tasks", "Deciding how much each Developer will work", "Just observing"],
    answer: [0],
    exp: "The Product Owner proposes how to increase value (the Why) and discusses the top Product Backlog items with the Developers (the What)." },
  { topic: "events", type: "single",
    q: "In Sprint Planning, who decides how the selected items will be turned into an Increment?",
    options: ["The Product Owner", "The Developers", "The Scrum Master", "The stakeholders"],
    answer: [1],
    exp: "The How is solely up to the Developers. The Product Owner clarifies questions and negotiates trade-offs without dictating how to do the work." },
  { topic: "events", type: "single",
    q: "What is the Product Owner's role in the Sprint Review?",
    options: ["Taking a leading role in collaborating with stakeholders, discussing the Increment and the market, and adapting the Product Backlog", "Individually approving or rejecting the Developers", "Presenting status slides", "The Product Owner does not participate"],
    answer: [0],
    exp: "In the Sprint Review, the Product Owner leads the conversation about progress toward the Product Goal, market changes, and what to do next." },
  { topic: "events", type: "tf",
    q: "In the Sprint Review, the Product Owner can discuss progress toward the Product Goal and likely delivery dates.",
    options: ["True", "False"],
    answer: [0],
    exp: "The Sprint Review is the time to inspect progress toward the Product Goal and adjust forecasts and the Product Backlog." },
  { topic: "events", type: "tf",
    q: "The Product Owner participates in the Sprint Retrospective as a member of the Scrum Team.",
    options: ["True", "False"],
    answer: [0],
    exp: "The Product Owner is a member of the Scrum Team and participates in the Sprint Retrospective, which inspects individuals, interactions, processes and tools." },
  { topic: "events", type: "single",
    q: "The Product Owner wants to attend the Daily Scrum to follow progress. What is the correct approach?",
    options: ["The Product Owner runs the meeting and demands status updates", "The Daily Scrum is for the Developers; the Product Owner only participates actively when working as a Developer", "The Product Owner is forbidden from being present", "The Product Owner should replace the Scrum Master"],
    answer: [1],
    exp: "The Daily Scrum is for the Developers. The Product Owner participates actively only when working on items in the Sprint Backlog." },
  { topic: "release", type: "single",
    q: "Who decides when to release an Increment to the market?",
    options: ["The Developers", "The Scrum Master", "The Product Owner", "The operations department, always"],
    answer: [2],
    exp: "The release decision belongs to the Product Owner, based on accumulated value, the market and risks." },
  { topic: "release", type: "tf",
    q: "Value is only truly delivered when an Increment that meets the Definition of Done is used by users.",
    options: ["True", "False"],
    answer: [0],
    exp: "Work that is not Done delivers no value. Value is realized when a Done, usable Increment reaches users." },
  { topic: "release", type: "single",
    q: "An Increment is Done, but the Product Owner decides not to release it now. Is this valid?",
    options: ["No, every Increment must be released immediately", "Yes, the release decision belongs to the Product Owner, but the Increment must be usable", "Only if the Scrum Master agrees", "Only in the last Sprint"],
    answer: [1],
    exp: "Being Done and being released are separate decisions. The Product Owner can accumulate value and release later, when it makes sense." },
  { topic: "release", type: "multi",
    q: "Which factors can the Product Owner consider when deciding on a release? (Choose 3)",
    options: ["Accumulated value for users", "Market timing and competition", "Risks of releasing or of waiting", "The number of hours worked in the Sprint"],
    answer: [0, 1, 2],
    exp: "A release decision considers value, market and risk. Hours worked do not indicate value." },
  { topic: "release", type: "tf",
    q: "Release Planning is a mandatory Scrum event.",
    options: ["True", "False"],
    answer: [1],
    exp: "Release Planning is not a Scrum event. Release planning is a practice the Product Owner may use in whatever way they choose." },
];
